### PR TITLE
Fixes #104 - sushi deposit links broken

### LINKED ISSUE #104: Several sushi deposit links don't work
Several sushiswap jars have deposit links that no longer work. They all start with `https://exchange.sushiswapclassic.org/#/add`

The redirects that occur link to a generic `swap` interface (not `add`) with only `eth` pre-loaded in the dropdown.

### PR DESCRIPTION
**Pull request by robstryker**
Signed-off-by: Rob Stryker <rob@oxbeef.net>

### CODE REVIEW

File: containers/Jars/jars.ts [hunk 1]
```diff
@@ -226,25 +226,25 @@ export const DEPOSIT_TOKENS_LINK = {
...
-    "https://exchange.sushiswapclassic.org/#/add/0xc5bddf9843308380375a611c18b50fb9341f502a/ETH",
+    "https://app.sushi.com/add/0xc5bddf9843308380375a611c18b50fb9341f502a/ETH",
   SUSHI_ETH_YVBOOST:
-    "https://exchange.sushiswapclassic.org/#/add/0x9d409a0A012CFbA9B15F6D4B36Ac57A46966Ab9a/ETH",
+    "https://app.sushi.com/add/0x9d409a0A012CFbA9B15F6D4B36Ac57A46966Ab9a/ETH",
   SUSHI_ETH:
-    "https://exchange.sushiswapclassic.org/#/add/0x6b3595068778dd592e39a122f4f5a5cf09c90fe2/ETH",
+    "https://app.sushi.com/add/0x6b3595068778dd592e39a122f4f5a5cf09c90fe2/ETH",
   SUSHI_ETH_ALCX:
     "https://app.sushi.com/add/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2/0xdbdb4d16eda451d0503b854cf79d55697f90c8df",
```
Comment (mannyreimi88) [inline containers/Jars/jars.ts:249]:
```suggestion
    "https://app.sushi.com/add/ETH/0xdBdb4d16EdA451D0503b854CF79D55697F90c8DF",
```

**Review by mannyreimi88 — APPROVED** [review]
